bf16: true
cutoff_len: 8000
dataset: train,validation,train_augmented
ddp_timeout: 180000000
do_train: true
finetuning_type: lora
flash_attn: disabled
gradient_accumulation_steps: 8
learning_rate: 0.0001
logging_steps: 5
lora_target: all
lr_scheduler_type: cosine
max_samples: 10000000
model_name_or_path: google/gemma-2-9b
num_train_epochs: 5
output_dir: models/sft-lora
overwrite_cache: true
overwrite_output_dir: true
per_device_train_batch_size: 2
plot_loss: true
preprocessing_num_workers: 16
report_to: tensorboard
save_strategy: epoch
stage: sft
template: gemma
warmup_ratio: 0.1

